language: php

services:
  - mysql

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

env:
  global:
    - WP_VERSION=latest
    - WP_MULTISITE=0
    - TEST_BUILD_DIR=${TRAVIS_BUILD_DIR}
    - GOOGLE_APPLICATION_CREDENTIALS=${HOME}/credentials.json
    - DB_HOST=localhost
    - COMPOSER_BIN_DIR=$(composer global config bin-dir --absolute)
    - PATH=${HOME}/google-cloud-sdk/bin:${COMPOSER_BIN_DIR}:${PATH}

matrix:
  include:
    - php: 5.6
      env: RUN_CS_FIXER=true
    - php: 7.0
    - php: 7.1

before_install:
  - composer global require phpunit/phpunit:^5.7 google/cloud-tools:dev-master
  - dump_credentials.php
  - install_test_deps.sh --gcloud
  - if [ "$RUN_CS_FIXER" = "true" ]; then install_test_deps.sh --cs-fixer; fi
  - mkdir -p build/logs

script:
# Run linter
- if [ "$RUN_CS_FIXER" = "true" ]; then ./php-cs-fixer fix --dry-run --diff; fi
# Run the tests in each of the sample directories
- scripts/run_tests.sh

after_success:
  - composer global require "php-coveralls/php-coveralls:^2.1"
  - travis_retry php-coveralls -v
